operating_systems = [{'Make': 'Acorn Computers', 'Operating_system': 'Arthur'},
                     {'Make': 'Acorn Computers', 'Operating_system': 'ARX'},
                     {'Make': 'Acorn Computers', 'Operating_system': 'MOS'},
                     {'Make': 'Acorn Computers', 'Operating_system': 'RISC iX'},
                     {'Make': 'Acorn Computers', 'Operating_system': 'RISC OS'},
                     {'Make': 'Amazon', 'Operating_system': 'Fire OS'},
                     {'Make': 'Amiga Inc.', 'Operating_system': 'AmigaOS'},
                     {'Make': 'Amiga Inc.', 'Operating_system': 'AmigaOS 1.0-3.9'},
                     {'Make': 'Amiga Inc.', 'Operating_system': 'AmigaOS 4'},
                     {'Make': 'Amiga Inc.', 'Operating_system': 'Amiga Unix'},
                     {'Make': 'Amstrad', 'Operating_system': 'AMSDOS'},
                     {'Make': 'Amstrad', 'Operating_system': 'Contiki'},
                     {'Make': 'Amstrad', 'Operating_system': 'CP/M 2.2'},
                     {'Make': 'Amstrad', 'Operating_system': 'CP/M Plus'},
                     {'Make': 'Amstrad', 'Operating_system': 'SymbOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple II'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple DOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple Pascal'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'ProDOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'GS/OS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'GNO/ME'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Contiki'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple III'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple SOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple Lisa'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple Macintosh'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Classic Mac OS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'A/UX'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'UNIX System V'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'BSD'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Copland'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'MkLinux'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Pink'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Rhapsody'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'macOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'macOS Server'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple Network Server'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'IBM AIX'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple MessagePad'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Newton OS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'iPhone'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'iPod Touch'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'iOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'iPad'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'iPadOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple Watch'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'watchOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Apple TV'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'tvOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'A/ROSE'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'bridgeOS'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'iPod software'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'iPod'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'NetBSD'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Airport Extreme'},
                     {'Make': 'Apple Inc.', 'Operating_system': 'Time Capsule'},
                     {'Make': '', 'Operating_system': 'Domain/OS'},
                     {'Make': '', 'Operating_system': 'Apollo/Domain'},
                     {'Make': '', 'Operating_system': 'Hewlett-Packard'},
                     {'Make': 'Atari', 'Operating_system': 'Atari DOS'},
                     {'Make': 'Atari', 'Operating_system': 'Atari TOS'},
                     {'Make': 'Atari', 'Operating_system': 'Atari MultiTOS'},
                     {'Make': 'Atari', 'Operating_system': 'Contiki'},
                     {'Make': 'BAE Systems', 'Operating_system': 'XTS-400'},
                     {'Make': 'Be Inc.', 'Operating_system': 'BeOS'},
                     {'Make': 'Be Inc.', 'Operating_system': 'BeIA'},
                     {'Make': 'Be Inc.', 'Operating_system': 'BeOS r5.1d0'},
                     {'Make': 'Be Inc.', 'Operating_system': 'magnussoft ZETA'},
                     {'Make': 'Be Inc.', 'Operating_system': 'BeOS r5.1d0'},
                     {'Make': 'Be Inc.', 'Operating_system': 'yellowTAB'},
                     {'Make': 'Bell Labs', 'Operating_system': 'Unix'},
                     {'Make': 'Bell Labs', 'Operating_system': 'Ken Thompson'},
                     {'Make': 'Bell Labs', 'Operating_system': 'Unix family'},
                     {'Make': 'Bell Labs', 'Operating_system': 'UNIX Time-Sharing System v6'},
                     {'Make': 'Bell Labs', 'Operating_system': 'PWB/UNIX'},
                     {'Make': 'Bell Labs', 'Operating_system': 'CB Unix'},
                     {'Make': 'Bell Labs', 'Operating_system': 'UNIX Time-Sharing System v7'},
                     {'Make': 'Bell Labs', 'Operating_system': 'Unix System III'},
                     {'Make': 'Bell Labs', 'Operating_system': 'Unix System V'},
                     {'Make': 'Bell Labs', 'Operating_system': 'UNIX Time-Sharing System v8'},
                     {'Make': 'Bell Labs', 'Operating_system': 'UNIX Time-Sharing System v9'},
                     {'Make': 'Bell Labs', 'Operating_system': 'UNIX Time-Sharing System v10'},
                     {'Make': '', 'Operating_system': 'Burroughs MCP'},
                     {'Make': 'Commodore International', 'Operating_system': 'GEOS'},
                     {'Make': 'Commodore International', 'Operating_system': 'AmigaOS'},
                     {'Make': 'Commodore International',
                      'Operating_system': 'AROS Research Operating System'},
                     {'Make': 'CloudMosa', 'Operating_system': 'Puffin OS'},
                     {'Make': 'Convergent Technologies',
                      'Operating_system': 'Convergent Technologies Operating System'},
                     {'Make': 'Convergent Technologies', 'Operating_system': 'Unisys'},
                     {'Make': 'Cromemco', 'Operating_system': 'Cromemco DOS'},
                     {'Make': 'Cromemco', 'Operating_system': 'CP/M'},
                     {'Make': 'Cromemco', 'Operating_system': 'Cromix'},
                     {'Make': 'Cromemco', 'Operating_system': 'Unix'},
                     {'Make': 'Cromemco', 'Operating_system': 'Cromemco'},
                     {'Make': 'Cromemco', 'Operating_system': 'Z80A'},
                     {'Make': 'Cromemco', 'Operating_system': '68000'},
                     {'Make': 'Data General', 'Operating_system': 'AOS'},
                     {'Make': 'Data General', 'Operating_system': 'Data General Eclipse'},
                     {'Make': 'Data General', 'Operating_system': 'AOS/VS'},
                     {'Make': 'Data General', 'Operating_system': 'DG/UX'},
                     {'Make': 'Data General', 'Operating_system': 'RDOS'},
                     {'Make': 'Data General', 'Operating_system': 'PC DOS'},
                     {'Make': 'Data General', 'Operating_system': 'MS-DOS'},
                     {'Make': 'Datapoint', 'Operating_system': 'Datapoint 2200'},
                     {'Make': '', 'Operating_system': 'Deos'},
                     {'Make': '', 'Operating_system': 'HeartOS'},
                     {'Make': '', 'Operating_system': 'CP/M'},
                     {'Make': '', 'Operating_system': 'CP/M'},
                     {'Make': '', 'Operating_system': 'Intel 8080'},
                     {'Make': '', 'Operating_system': '8085'},
                     {'Make': '', 'Operating_system': 'Zilog Z80'},
                     {'Make': '', 'Operating_system': 'Personal CP/M'},
                     {'Make': '', 'Operating_system': 'CP/M Plus'},
                     {'Make': '', 'Operating_system': 'CP/M-68K'},
                     {'Make': '', 'Operating_system': 'Motorola 68000'},
                     {'Make': '', 'Operating_system': 'CP/M-8000'},
                     {'Make': '', 'Operating_system': 'Zilog Z8000'},
                     {'Make': '', 'Operating_system': 'CP/M-86'},
                     {'Make': '', 'Operating_system': 'Intel 8088'},
                     {'Make': '', 'Operating_system': '8086'},
                     {'Make': '', 'Operating_system': 'CP/M-86 Plus'},
                     {'Make': '', 'Operating_system': 'Personal CP/M-86'},
                     {'Make': '', 'Operating_system': 'MP/M'},
                     {'Make': '', 'Operating_system': 'MP/M II'},
                     {'Make': '', 'Operating_system': 'MP/M-86'},
                     {'Make': '', 'Operating_system': 'MP/M 8-16'},
                     {'Make': '', 'Operating_system': 'Concurrent CP/M'},
                     {'Make': '', 'Operating_system': 'Concurrent CP/M-86'},
                     {'Make': '', 'Operating_system': 'Concurrent CP/M 8-16'},
                     {'Make': '', 'Operating_system': 'Concurrent CP/M-68K'},
                     {'Make': '', 'Operating_system': 'DOS'},
                     {'Make': '', 'Operating_system': 'Concurrent DOS'},
                     {'Make': '', 'Operating_system': 'Concurrent PC DOS'},
                     {'Make': '', 'Operating_system': 'Concurrent DOS 8-16'},
                     {'Make': '', 'Operating_system': 'Concurrent DOS 286'},
                     {'Make': '', 'Operating_system': 'Concurrent DOS XM'},
                     {'Make': '', 'Operating_system': 'Concurrent DOS 386'},
                     {'Make': '', 'Operating_system': 'Concurrent DOS 386/MGE'},
                     {'Make': '', 'Operating_system': 'Concurrent DOS 68K'},
                     {'Make': '', 'Operating_system': 'FlexOS'},
                     {'Make': '', 'Operating_system': 'FlexOS 186'},
                     {'Make': '', 'Operating_system': 'FlexOS 286'},
                     {'Make': '', 'Operating_system': 'Siemens S5-DOS/MT'},
                     {'Make': '', 'Operating_system': 'IBM 4680 OS'},
                     {'Make': '', 'Operating_system': 'POS'},
                     {'Make': '', 'Operating_system': 'IBM 4690 OS'},
                     {'Make': '', 'Operating_system': 'Toshiba 4690 OS'},
                     {'Make': '', 'Operating_system': 'FlexOS 386'},
                     {'Make': '', 'Operating_system': 'IBM 4690 OS'},
                     {'Make': '', 'Operating_system': 'Toshiba 4690 OS'},
                     {'Make': '', 'Operating_system': 'FlexOS 68K'},
                     {'Make': '', 'Operating_system': 'Multiuser DOS'},
                     {'Make': '', 'Operating_system': 'CCI Multiuser DOS'},
                     {'Make': '', 'Operating_system': 'Datapac Multiuser DOS'},
                     {'Make': '', 'Operating_system': 'Datapac System Manager'},
                     {'Make': '', 'Operating_system': 'IMS Multiuser DOS'},
                     {'Make': '', 'Operating_system': 'REAL/32'},
                     {'Make': '', 'Operating_system': 'REAL/NG'},
                     {'Make': '', 'Operating_system': 'DOS Plus'},
                     {'Make': '', 'Operating_system': 'DR-DOS'},
                     {'Make': '', 'Operating_system': 'PalmDOS'},
                     {'Make': '', 'Operating_system': '"Star Trek"'},
                     {'Make': '', 'Operating_system': 'Novell DOS'},
                     {'Make': '', 'Operating_system': 'OpenDOS'},
                     {'Make': '', 'Operating_system': 'DR-DOS'},
                     {'Make': '', 'Operating_system': 'Batch-11/DOS-11'},
                     {'Make': '', 'Operating_system': 'OS/8'},
                     {'Make': '', 'Operating_system': 'RSTS/E'},
                     {'Make': '', 'Operating_system': 'PDP-11s'},
                     {'Make': '', 'Operating_system': 'RSX-11'},
                     {'Make': '', 'Operating_system': 'RT-11'},
                     {'Make': '', 'Operating_system': 'TOPS-10'},
                     {'Make': '', 'Operating_system': 'TENEX'},
                     {'Make': '', 'Operating_system': 'TOPS-20'},
                     {'Make': '', 'Operating_system': 'BBN'},
                     {'Make': '', 'Operating_system': 'TOPS-20'},
                     {'Make': '', 'Operating_system': 'DEC MICA'},
                     {'Make': '', 'Operating_system': 'DEC PRISM'},
                     {'Make': '', 'Operating_system': 'Digital UNIX'},
                     {'Make': '', 'Operating_system': 'Tru64 UNIX'},
                     {'Make': '', 'Operating_system': 'Ultrix'},
                     {'Make': '', 'Operating_system': 'VMS'},
                     {'Make': '', 'Operating_system': 'DEC'},
                     {'Make': '', 'Operating_system': 'VAX'},
                     {'Make': '', 'Operating_system': 'Alpha'},
                     {'Make': '', 'Operating_system': 'Itanium i2 and i4'},
                     {'Make': '', 'Operating_system': 'WAITS'},
                     {'Make': 'ENEA AB', 'Operating_system': 'OSE'},
                     {'Make': 'Fujitsu', 'Operating_system': 'Towns OS'},
                     {'Make': 'Fujitsu', 'Operating_system': 'OS/IV'},
                     {'Make': 'Fujitsu', 'Operating_system': 'MSP'},
                     {'Make': 'Fujitsu', 'Operating_system': 'MSP-EX'},
                     {'Make': '',
                      'Operating_system': 'Real-Time Multiprogramming Operating System'},
                     {'Make': '', 'Operating_system': 'GCOS'},
                     {'Make': '', 'Operating_system': 'Multics'},
                     {'Make': 'Green Hills Software', 'Operating_system': 'INTEGRITY'},
                     {'Make': 'Green Hills Software', 'Operating_system': 'INTEGRITY-178B'},
                     {'Make': 'Green Hills Software', 'Operating_system': 'INTEGRITY'},
                     {'Make': 'Green Hills Software', 'Operating_system': 'µ-velOSity'},
                     {'Make': 'Green Hills Software', 'Operating_system': 'microkernel'},
                     {'Make': 'Harris Corporation', 'Operating_system': 'Vulcan O/S'},
                     {'Make': 'Harris Corporation', 'Operating_system': 'Harris UNIX'},
                     {'Make': '', 'Operating_system': 'HDOS'},
                     {'Make': '', 'Operating_system': 'H8'},
                     {'Make': '', 'Operating_system': 'Zenith Z-89'},
                     {'Make': '', 'Operating_system': 'HT-11'},
                     {'Make': '', 'Operating_system': 'RT-11'},
                     {'Make': '', 'Operating_system': 'Heathkit H11'},
                     {'Make': '', 'Operating_system': 'HP Multi-Programming Executive'},
                     {'Make': '', 'Operating_system': 'HP-UX'},
                     {'Make': 'Honeywell', 'Operating_system': 'CP-6'},
                     {'Make': 'Huawei', 'Operating_system': 'Harmony OS'},
                     {'Make': 'Huawei', 'Operating_system': 'LiteOS'},
                     {'Make': 'Intel Corporation', 'Operating_system': 'iRMX'},
                     {'Make': 'Intel Corporation', 'Operating_system': 'ISIS'},
                     {'Make': 'Intel Corporation', 'Operating_system': 'ISIS-II'},
                     {'Make': 'Intel Corporation', 'Operating_system': 'Intellec'},
                     {'Make': 'Intel Corporation', 'Operating_system': 'PL/M'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'J'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'MultiJob'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'GEORGE'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'ICL'},
                     {'Make': 'International Computers Limited',
                      'Operating_system': '1900 series'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'Executive'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'TME'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'ICL VME'},
                     {'Make': 'International Computers Limited',
                      'Operating_system': 'ICL 2900 Series'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'S3'},
                     {'Make': 'International Computers Limited', 'Operating_system': 'VME/K'},
                     {'Make': 'Jide', 'Operating_system': 'Remix OS'},
                     {'Make': 'Jolla', 'Operating_system': 'Sailfish OS'},
                     {'Make': 'KaiOS', 'Operating_system': 'KaiOS'},
                     {'Make': '', 'Operating_system': 'LynxOS'},
                     {'Make': 'Meizu', 'Operating_system': 'Flyme OS'},
                     {'Make': 'Micrium Inc.', 'Operating_system': 'MicroC/OS-II'},
                     {'Make': 'Micrium Inc.', 'Operating_system': 'MicroC/OS-III'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Xenix'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'SCO'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'MS-DOS'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'MSX-DOS'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'DOS/V'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'OS/2'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 1.0'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 2.0'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 3.0'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 3.1x'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows for Workgroups 3.1'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 3.2'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows for Workgroups 3.11'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 95'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 98'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Millennium Edition'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows NT'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows NT 3.1'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows NT 3.5'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows NT 3.51'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows NT 4.0'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 2000'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows XP'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Server 2003'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Fundamentals for Legacy PCs'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Vista'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Azure'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Home Server'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Server 2008'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 7'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Phone 7'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Server 2008 R2'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Home Server 2011'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 8'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows RT'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Phone 8'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Server 2012'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 8.1'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Phone 8.1'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Server 2012 R2'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 10'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 10 Mobile'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Server 2016'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Server 2019'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows 11'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows CE'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows CE 3.0'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows CE 5.0'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Embedded CE 6.0'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Embedded Compact 7'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Windows Embedded Compact 2013'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Windows Mobile'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Singularity'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'managed code'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'C#'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Midori'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Xbox system software'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Xbox 360 system software'},
                     {'Make': 'Microsoft Corporation',
                      'Operating_system': 'Xbox One system software'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'Azure Sphere'},
                     {'Make': 'Microsoft Corporation', 'Operating_system': 'ThreadX'},
                     {'Make': 'MITS', 'Operating_system': 'Altair DOS'},
                     {'Make': 'MITS', 'Operating_system': 'Altair 8800'},
                     {'Make': 'MITS', 'Operating_system': 'citation needed'},
                     {'Make': 'MontaVista', 'Operating_system': 'Mobilinux'},
                     {'Make': 'NCR Corporation', 'Operating_system': 'TMX'},
                     {'Make': 'NCR Corporation', 'Operating_system': 'IMOS'},
                     {'Make': 'NCR Corporation', 'Operating_system': 'citation needed'},
                     {'Make': 'NCR Corporation', 'Operating_system': 'VRX'},
                     {'Make': 'Nintendo', 'Operating_system': 'ES'},
                     {'Make': 'NeXT', 'Operating_system': 'NeXTSTEP'},
                     {'Make': 'Novell', 'Operating_system': 'NetWare'},
                     {'Make': 'Novell', 'Operating_system': 'UnixWare'},
                     {'Make': 'Novell', 'Operating_system': 'Novell "SuperNOS"'},
                     {'Make': 'Novell', 'Operating_system': 'Novell "Corsair"'},
                     {'Make': 'Novell', 'Operating_system': 'Novell "Exposé"'},
                     {'Make': 'Novell', 'Operating_system': 'Open Enterprise Server'},
                     {'Make': 'Open Mobile Platform', 'Operating_system': 'Aurora OS'},
                     {'Make': 'Open Mobile Platform', 'Operating_system': 'Aurora OS'},
                     {'Make': 'Quadros Systems', 'Operating_system': 'RTXC Quadros'},
                     {'Make': 'RCA', 'Operating_system': 'Time Sharing Operating System'},
                     {'Make': 'RoweBots', 'Operating_system': 'DSPnano RTOS'},
                     {'Make': 'Samsung Electronics', 'Operating_system': 'Bada'},
                     {'Make': 'Samsung Electronics', 'Operating_system': 'Tizen'},
                     {'Make': 'Samsung Electronics', 'Operating_system': 'Orsay'},
                     {'Make': 'Samsung Electronics', 'Operating_system': 'One UI'},
                     {'Make': 'Sinclair Research', 'Operating_system': 'Sinclair BASIC'},
                     {'Make': 'Sinclair Research', 'Operating_system': 'Sinclair Research'},
                     {'Make': 'Sinclair Research', 'Operating_system': 'Timex Sinclair'},
                     {'Make': '', 'Operating_system': 'Xenix'},
                     {'Make': '', 'Operating_system': 'Xenix'},
                     {'Make': '', 'Operating_system': 'Xenix'},
                     {'Make': '', 'Operating_system': 'SCO Unix'},
                     {'Make': '', 'Operating_system': 'SCO Open Desktop'},
                     {'Make': '', 'Operating_system': 'SCO Unix'},
                     {'Make': '', 'Operating_system': 'SCO OpenServer'},
                     {'Make': '', 'Operating_system': 'SCO OpenServer'},
                     {'Make': '', 'Operating_system': 'UnixWare'},
                     {'Make': '', 'Operating_system': 'UnixWare'},
                     {'Make': '', 'Operating_system': 'UnixWare'},
                     {'Make': '', 'Operating_system': 'SCO'},
                     {'Make': '', 'Operating_system': 'Berkeley Timesharing System'},
                     {'Make': '', 'Operating_system': 'SDS 940'},
                     {'Make': 'SYSGO', 'Operating_system': 'PikeOS'},
                     {'Make': '', 'Operating_system': 'NonStop OS'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'TRSDOS'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'TRS-80'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'Color BASIC'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'TRS-80 Color Computer'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'NewDos/80'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'DeskMate'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'Tandy 1000'},
                     {'Make': 'Tandy Corporation', 'Operating_system': 'citation needed'},
                     {'Make': '', 'Operating_system': 'Edos'},
                     {'Make': '', 'Operating_system': 'DOS/360'},
                     {'Make': '', 'Operating_system': 'DOS/VS'},
                     {'Make': '', 'Operating_system': 'DOS/VSE'},
                     {'Make': '', 'Operating_system': 'System/360'},
                     {'Make': '', 'Operating_system': 'System/370'},
                     {'Make': 'Texas Instruments', 'Operating_system': 'TI-RTOS Kernel'},
                     {'Make': 'TRON Project', 'Operating_system': 'TRON'},
                     {'Make': 'TRON Project', 'Operating_system': 'real-time operating system'},
                     {'Make': 'TRON Project', 'Operating_system': 'kernel'},
                     {'Make': 'TRON Project', 'Operating_system': 'T-Kernel'},
                     {'Make': '', 'Operating_system': 'EXEC I'},
                     {'Make': '', 'Operating_system': 'EXEC II'},
                     {'Make': '', 'Operating_system': 'EXEC 8'},
                     {'Make': '', 'Operating_system': 'OS 2200'},
                     {'Make': '', 'Operating_system': 'VS/9'},
                     {'Make': '', 'Operating_system': 'RCA TSOS'},
                     {'Make': 'Wang Laboratories', 'Operating_system': 'WPS'},
                     {'Make': 'Wang Laboratories', 'Operating_system': 'OIS'},
                     {'Make': 'Wind River Systems', 'Operating_system': 'VxWorks'},
                     {'Make': 'Zilog', 'Operating_system': 'Z80-RIO'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'MINIX'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Andrew S. Tanenbaum'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Netherlands'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'BSD'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'DEC'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'VAX'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'FreeBSD'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'CSRG'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'DragonFlyBSD'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'MidnightBSD'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'GhostBSD'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'TrueOS'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'NetBSD'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'OpenBSD'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Bitrig'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Darwin'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'GNU'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Linux'},
                     {'Make': 'Unix or Unix-like',
                      'Operating_system': 'List of Linux distributions'},
                     {'Make': 'Unix or Unix-like',
                      'Operating_system': 'GNU/Linux naming controversy'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Android'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Android-x86'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Remix OS'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Redox'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'OpenSolaris'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'illumos'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'OpenSolaris'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Solaris'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'OpenIndiana'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'OS/Net'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'OpenSolaris'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Solaris'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Nexenta OS'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'SmartOS'},
                     {'Make': 'Unix or Unix-like',
                      'Operating_system': 'Kernel-based Virtual Machine'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'RTEMS'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Syllable Desktop'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'VSTa'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Plurix'},
                     {'Make': 'Unix or Unix-like',
                      'Operating_system': 'Federal University of Rio de Janeiro'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'TUNIS'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Xv6'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'SerenityOS'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Microsoft Windows'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Mac OS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Cosmos'},
                     {'Make': 'Non-Unix', 'Operating_system': 'FreeDOS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Genode'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Ghost OS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Haiku'},
                     {'Make': 'Non-Unix', 'Operating_system': 'BeOS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Incompatible Timesharing System'},
                     {'Make': 'Non-Unix', 'Operating_system': 'macro assembler'},
                     {'Make': 'Non-Unix', 'Operating_system': 'PDP-6'},
                     {'Make': 'Non-Unix', 'Operating_system': 'PDP-10'},
                     {'Make': 'Non-Unix', 'Operating_system': 'MIT'},
                     {'Make': 'Non-Unix', 'Operating_system': 'osFree'},
                     {'Make': 'Non-Unix', 'Operating_system': 'OSv'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Phantom OS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'ReactOS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Windows NT'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Windows XP'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Windows 2000'},
                     {'Make': 'Non-Unix', 'Operating_system': 'SharpOS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'TempleOS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Visopsys'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Plan 9 from Bell Labs'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Bell Labs'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Inferno'},
                     {'Make': 'Unix or Unix-like', 'Operating_system': 'Research Unix'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Amoeba'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Andrew S. Tanenbaum'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Barrelfish'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Croquet'},
                     {'Make': 'Non-Unix', 'Operating_system': 'EROS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'CapROS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Harmony'},
                     {'Make': 'Non-Unix', 'Operating_system': 'HelenOS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'House'},
                     {'Make': 'Non-Unix', 'Operating_system': 'ILIOS'},
                     {'Make': 'Non-Unix', 'Operating_system': 'L4'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Mach'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Carnegie Mellon University'},
                     {'Make': 'Non-Unix', 'Operating_system': 'NeXTSTEP'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Nemesis'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Singularity'},
                     {'Make': 'Non-Unix', 'Operating_system': 'managed code'},
                     {'Make': 'Non-Unix', 'Operating_system': 'dependable'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Spring'},
                     {'Make': 'Non-Unix', 'Operating_system': 'THE multiprogramming system'},
                     {'Make': 'Non-Unix',
                      'Operating_system': 'Eindhoven University of Technology'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Thoth'},
                     {'Make': 'Non-Unix', 'Operating_system': 'University of Waterloo'},
                     {'Make': 'Non-Unix', 'Operating_system': 'V'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Verve'},
                     {'Make': 'Non-Unix', 'Operating_system': 'type safety'},
                     {'Make': 'Non-Unix', 'Operating_system': 'memory safety'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Xinu'},
                     {'Make': 'Non-Unix', 'Operating_system': 'Douglas E. Comer'},
                     {'Make': 'Routers', 'Operating_system': 'CatOS'},
                     {'Make': 'Routers', 'Operating_system': 'Cisco Systems'},
                     {'Make': 'Routers', 'Operating_system': 'Cisco IOS'},
                     {'Make': 'Routers', 'Operating_system': 'Cisco Systems'},
                     {'Make': 'Routers', 'Operating_system': 'Inferno'},
                     {'Make': 'Routers', 'Operating_system': 'Bell Labs'},
                     {'Make': 'Routers', 'Operating_system': 'IOS-XR'},
                     {'Make': 'Routers', 'Operating_system': 'Cisco Systems'},
                     {'Make': 'Routers', 'Operating_system': 'JunOS'},
                     {'Make': 'Routers', 'Operating_system': 'Juniper Networks'},
                     {'Make': 'Routers', 'Operating_system': 'LANCOM Systems'},
                     {'Make': 'Routers', 'Operating_system': 'Linux'},
                     {'Make': 'Routers', 'Operating_system': 'OpenWrt'},
                     {'Make': 'Routers', 'Operating_system': 'DD-WRT'},
                     {'Make': 'Routers', 'Operating_system': 'LEDE'},
                     {'Make': 'Routers', 'Operating_system': 'Gargoyle'},
                     {'Make': 'Routers', 'Operating_system': 'LibreCMC'},
                     {'Make': 'Routers', 'Operating_system': 'Zeroshell'},
                     {'Make': 'Routers', 'Operating_system': 'RTOS'},
                     {'Make': 'Routers', 'Operating_system': 'm0n0wall'},
                     {'Make': 'Routers', 'Operating_system': 'OPNsense'},
                     {'Make': 'Routers', 'Operating_system': 'pfsense'},
                     {'Make': 'Routers',
                      'Operating_system': 'List of wireless router firmware projects'},
                     {'Make': 'Other embedded', 'Operating_system': 'Apache Mynewt'},
                     {'Make': 'Other embedded', 'Operating_system': 'ChibiOS/RT'},
                     {'Make': 'Other embedded', 'Operating_system': 'Contiki'},
                     {'Make': 'Other embedded', 'Operating_system': 'ERIKA Enterprise'},
                     {'Make': 'Other embedded', 'Operating_system': 'eCos'},
                     {'Make': 'Other embedded', 'Operating_system': 'NetBSD'},
                     {'Make': 'Other embedded', 'Operating_system': 'Nucleus RTOS'},
                     {'Make': 'Other embedded', 'Operating_system': 'NuttX'},
                     {'Make': 'Other embedded', 'Operating_system': 'Minix'},
                     {'Make': 'Other embedded', 'Operating_system': 'NCOS'},
                     {'Make': 'Other embedded',
                      'Operating_system': 'freeRTOS, openRTOS, safeRTOS'},
                     {'Make': 'Other embedded', 'Operating_system': 'OpenEmbedded'},
                     {'Make': 'Other embedded', 'Operating_system': 'Yocto Project'},
                     {'Make': 'Other embedded', 'Operating_system': 'pSOS'},
                     {'Make': 'Other embedded', 'Operating_system': 'QNX'},
                     {'Make': 'Other embedded', 'Operating_system': 'REX OS'},
                     {'Make': 'Other embedded', 'Operating_system': 'RIOT'},
                     {'Make': 'Other embedded', 'Operating_system': 'ROM-DOS'},
                     {'Make': 'Other embedded', 'Operating_system': 'TinyOS'},
                     {'Make': 'Other embedded', 'Operating_system': 'ThreadX'},
                     {'Make': 'Other embedded', 'Operating_system': 'RT-Thread'},
                     {'Make': 'Other embedded', 'Operating_system': 'DSPnano RTOS'},
                     {'Make': 'Other embedded', 'Operating_system': 'Windows IoT'},
                     {'Make': 'Other embedded', 'Operating_system': 'Windows Embedded'},
                     {'Make': 'Other embedded', 'Operating_system': 'Windows CE'},
                     {'Make': 'Other embedded', 'Operating_system': 'Windows IoT Core'},
                     {'Make': 'Other embedded', 'Operating_system': 'Windows IoT Enterprise'},
                     {'Make': 'Other embedded', 'Operating_system': 'VxWorks'},
                     {'Make': 'Other embedded', 'Operating_system': 'Wombat'},
                     {'Make': 'Other embedded', 'Operating_system': 'microkernel'},
                     {'Make': 'Other embedded', 'Operating_system': 'real-time'},
                     {'Make': 'Other embedded', 'Operating_system': 'embedded'},
                     {'Make': 'Other embedded', 'Operating_system': 'Zephyr'},
                     {'Make': 'LEGO Mindstorms', 'Operating_system': 'brickOS'},
                     {'Make': 'LEGO Mindstorms', 'Operating_system': 'leJOS'},
                     {'Make': 'Category links', 'Operating_system': 'Operating systems'},
                     {'Make': 'Category links', 'Operating_system': 'Embedded operating systems'},
                     {'Make': 'Category links', 'Operating_system': 'Real-time operating systems'}]
