os_names = [{'os_maker': 'Acorn Computers', 'os_name': 'Arthur'},
            {'os_maker': 'Acorn Computers', 'os_name': 'ARX'},
            {'os_maker': 'Acorn Computers', 'os_name': 'MOS'},
            {'os_maker': 'Acorn Computers', 'os_name': 'RISC iX'},
            {'os_maker': 'Acorn Computers', 'os_name': 'RISC OS'},
            {'os_maker': 'Amazon', 'os_name': 'Fire OS'},
            {'os_maker': 'Amiga Inc.', 'os_name': 'AmigaOS'},
            {'os_maker': 'Amiga Inc.', 'os_name': 'AmigaOS 1.0-3.9'},
            {'os_maker': 'Amiga Inc.', 'os_name': 'AmigaOS 4'},
            {'os_maker': 'Amiga Inc.', 'os_name': 'Amiga Unix'},
            {'os_maker': 'Amstrad', 'os_name': 'AMSDOS'},
            {'os_maker': 'Amstrad', 'os_name': 'Contiki'},
            {'os_maker': 'Amstrad', 'os_name': 'CP/M 2.2'},
            {'os_maker': 'Amstrad', 'os_name': 'CP/M Plus'},
            {'os_maker': 'Amstrad', 'os_name': 'SymbOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple II'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple DOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple Pascal'},
            {'os_maker': 'Apple Inc.', 'os_name': 'ProDOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'GS/OS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'GNO/ME'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Contiki'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple III'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple SOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple Lisa'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple Macintosh'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Classic Mac OS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'A/UX'},
            {'os_maker': 'Apple Inc.', 'os_name': 'UNIX System V'},
            {'os_maker': 'Apple Inc.', 'os_name': 'BSD'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Copland'},
            {'os_maker': 'Apple Inc.', 'os_name': 'MkLinux'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Pink'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Rhapsody'},
            {'os_maker': 'Apple Inc.', 'os_name': 'macOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'macOS Server'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple Network Server'},
            {'os_maker': 'Apple Inc.', 'os_name': 'IBM AIX'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple MessagePad'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Newton OS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'iPhone'},
            {'os_maker': 'Apple Inc.', 'os_name': 'iPod Touch'},
            {'os_maker': 'Apple Inc.', 'os_name': 'iOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'iPad'},
            {'os_maker': 'Apple Inc.', 'os_name': 'iPadOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple Watch'},
            {'os_maker': 'Apple Inc.', 'os_name': 'watchOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Apple TV'},
            {'os_maker': 'Apple Inc.', 'os_name': 'tvOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'A/ROSE'},
            {'os_maker': 'Apple Inc.', 'os_name': 'bridgeOS'},
            {'os_maker': 'Apple Inc.', 'os_name': 'iPod faker_software'},
            {'os_maker': 'Apple Inc.', 'os_name': 'iPod'},
            {'os_maker': 'Apple Inc.', 'os_name': 'NetBSD'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Airport Extreme'},
            {'os_maker': 'Apple Inc.', 'os_name': 'Time Capsule'},
            {'os_maker': '', 'os_name': 'Domain/OS'},
            {'os_maker': '', 'os_name': 'Apollo/Domain'},
            {'os_maker': '', 'os_name': 'Hewlett-Packard'},
            {'os_maker': 'Atari', 'os_name': 'Atari DOS'},
            {'os_maker': 'Atari', 'os_name': 'Atari TOS'},
            {'os_maker': 'Atari', 'os_name': 'Atari MultiTOS'},
            {'os_maker': 'Atari', 'os_name': 'Contiki'},
            {'os_maker': 'BAE Systems', 'os_name': 'XTS-400'},
            {'os_maker': 'Be Inc.', 'os_name': 'BeOS'},
            {'os_maker': 'Be Inc.', 'os_name': 'BeIA'},
            {'os_maker': 'Be Inc.', 'os_name': 'BeOS r5.1d0'},
            {'os_maker': 'Be Inc.', 'os_name': 'magnussoft ZETA'},
            {'os_maker': 'Be Inc.', 'os_name': 'BeOS r5.1d0'},
            {'os_maker': 'Be Inc.', 'os_name': 'yellowTAB'},
            {'os_maker': 'Bell Labs', 'os_name': 'Unix'},
            {'os_maker': 'Bell Labs', 'os_name': 'Ken Thompson'},
            {'os_maker': 'Bell Labs', 'os_name': 'Unix family'},
            {'os_maker': 'Bell Labs', 'os_name': 'UNIX Time-Sharing System v6'},
            {'os_maker': 'Bell Labs', 'os_name': 'PWB/UNIX'},
            {'os_maker': 'Bell Labs', 'os_name': 'CB Unix'},
            {'os_maker': 'Bell Labs', 'os_name': 'UNIX Time-Sharing System v7'},
            {'os_maker': 'Bell Labs', 'os_name': 'Unix System III'},
            {'os_maker': 'Bell Labs', 'os_name': 'Unix System V'},
            {'os_maker': 'Bell Labs', 'os_name': 'UNIX Time-Sharing System v8'},
            {'os_maker': 'Bell Labs', 'os_name': 'UNIX Time-Sharing System v9'},
            {'os_maker': 'Bell Labs', 'os_name': 'UNIX Time-Sharing System v10'},
            {'os_maker': '', 'os_name': 'Burroughs MCP'},
            {'os_maker': 'Commodore International', 'os_name': 'GEOS'},
            {'os_maker': 'Commodore International', 'os_name': 'AmigaOS'},
            {'os_maker': 'Commodore International',
             'os_name': 'AROS Research Operating System'},
            {'os_maker': 'CloudMosa', 'os_name': 'Puffin OS'},
            {'os_maker': 'Convergent Technologies',
             'os_name': 'Convergent Technologies Operating System'},
            {'os_maker': 'Convergent Technologies', 'os_name': 'Unisys'},
            {'os_maker': 'Cromemco', 'os_name': 'Cromemco DOS'},
            {'os_maker': 'Cromemco', 'os_name': 'CP/M'},
            {'os_maker': 'Cromemco', 'os_name': 'Cromix'},
            {'os_maker': 'Cromemco', 'os_name': 'Unix'},
            {'os_maker': 'Cromemco', 'os_name': 'Cromemco'},
            {'os_maker': 'Cromemco', 'os_name': 'Z80A'},
            {'os_maker': 'Cromemco', 'os_name': '68000'},
            {'os_maker': 'Data General', 'os_name': 'AOS'},
            {'os_maker': 'Data General', 'os_name': 'Data General Eclipse'},
            {'os_maker': 'Data General', 'os_name': 'AOS/VS'},
            {'os_maker': 'Data General', 'os_name': 'DG/UX'},
            {'os_maker': 'Data General', 'os_name': 'RDOS'},
            {'os_maker': 'Data General', 'os_name': 'PC DOS'},
            {'os_maker': 'Data General', 'os_name': 'MS-DOS'},
            {'os_maker': 'Datapoint', 'os_name': 'Datapoint 2200'},
            {'os_maker': '', 'os_name': 'Deos'},
            {'os_maker': '', 'os_name': 'HeartOS'},
            {'os_maker': '', 'os_name': 'CP/M'},
            {'os_maker': '', 'os_name': 'CP/M'},
            {'os_maker': '', 'os_name': 'Intel 8080'},
            {'os_maker': '', 'os_name': '8085'},
            {'os_maker': '', 'os_name': 'Zilog Z80'},
            {'os_maker': '', 'os_name': 'Personal CP/M'},
            {'os_maker': '', 'os_name': 'CP/M Plus'},
            {'os_maker': '', 'os_name': 'CP/M-68K'},
            {'os_maker': '', 'os_name': 'Motorola 68000'},
            {'os_maker': '', 'os_name': 'CP/M-8000'},
            {'os_maker': '', 'os_name': 'Zilog Z8000'},
            {'os_maker': '', 'os_name': 'CP/M-86'},
            {'os_maker': '', 'os_name': 'Intel 8088'},
            {'os_maker': '', 'os_name': '8086'},
            {'os_maker': '', 'os_name': 'CP/M-86 Plus'},
            {'os_maker': '', 'os_name': 'Personal CP/M-86'},
            {'os_maker': '', 'os_name': 'MP/M'},
            {'os_maker': '', 'os_name': 'MP/M II'},
            {'os_maker': '', 'os_name': 'MP/M-86'},
            {'os_maker': '', 'os_name': 'MP/M 8-16'},
            {'os_maker': '', 'os_name': 'Concurrent CP/M'},
            {'os_maker': '', 'os_name': 'Concurrent CP/M-86'},
            {'os_maker': '', 'os_name': 'Concurrent CP/M 8-16'},
            {'os_maker': '', 'os_name': 'Concurrent CP/M-68K'},
            {'os_maker': '', 'os_name': 'DOS'},
            {'os_maker': '', 'os_name': 'Concurrent DOS'},
            {'os_maker': '', 'os_name': 'Concurrent PC DOS'},
            {'os_maker': '', 'os_name': 'Concurrent DOS 8-16'},
            {'os_maker': '', 'os_name': 'Concurrent DOS 286'},
            {'os_maker': '', 'os_name': 'Concurrent DOS XM'},
            {'os_maker': '', 'os_name': 'Concurrent DOS 386'},
            {'os_maker': '', 'os_name': 'Concurrent DOS 386/MGE'},
            {'os_maker': '', 'os_name': 'Concurrent DOS 68K'},
            {'os_maker': '', 'os_name': 'FlexOS'},
            {'os_maker': '', 'os_name': 'FlexOS 186'},
            {'os_maker': '', 'os_name': 'FlexOS 286'},
            {'os_maker': '', 'os_name': 'Siemens S5-DOS/MT'},
            {'os_maker': '', 'os_name': 'IBM 4680 OS'},
            {'os_maker': '', 'os_name': 'POS'},
            {'os_maker': '', 'os_name': 'IBM 4690 OS'},
            {'os_maker': '', 'os_name': 'Toshiba 4690 OS'},
            {'os_maker': '', 'os_name': 'FlexOS 386'},
            {'os_maker': '', 'os_name': 'IBM 4690 OS'},
            {'os_maker': '', 'os_name': 'Toshiba 4690 OS'},
            {'os_maker': '', 'os_name': 'FlexOS 68K'},
            {'os_maker': '', 'os_name': 'Multiuser DOS'},
            {'os_maker': '', 'os_name': 'CCI Multiuser DOS'},
            {'os_maker': '', 'os_name': 'Datapac Multiuser DOS'},
            {'os_maker': '', 'os_name': 'Datapac System Manager'},
            {'os_maker': '', 'os_name': 'IMS Multiuser DOS'},
            {'os_maker': '', 'os_name': 'REAL/32'},
            {'os_maker': '', 'os_name': 'REAL/NG'},
            {'os_maker': '', 'os_name': 'DOS Plus'},
            {'os_maker': '', 'os_name': 'DR-DOS'},
            {'os_maker': '', 'os_name': 'PalmDOS'},
            {'os_maker': '', 'os_name': '"Star Trek"'},
            {'os_maker': '', 'os_name': 'Novell DOS'},
            {'os_maker': '', 'os_name': 'OpenDOS'},
            {'os_maker': '', 'os_name': 'DR-DOS'},
            {'os_maker': '', 'os_name': 'Batch-11/DOS-11'},
            {'os_maker': '', 'os_name': 'OS/8'},
            {'os_maker': '', 'os_name': 'RSTS/E'},
            {'os_maker': '', 'os_name': 'PDP-11s'},
            {'os_maker': '', 'os_name': 'RSX-11'},
            {'os_maker': '', 'os_name': 'RT-11'},
            {'os_maker': '', 'os_name': 'TOPS-10'},
            {'os_maker': '', 'os_name': 'TENEX'},
            {'os_maker': '', 'os_name': 'TOPS-20'},
            {'os_maker': '', 'os_name': 'BBN'},
            {'os_maker': '', 'os_name': 'TOPS-20'},
            {'os_maker': '', 'os_name': 'DEC MICA'},
            {'os_maker': '', 'os_name': 'DEC PRISM'},
            {'os_maker': '', 'os_name': 'Digital UNIX'},
            {'os_maker': '', 'os_name': 'Tru64 UNIX'},
            {'os_maker': '', 'os_name': 'Ultrix'},
            {'os_maker': '', 'os_name': 'VMS'},
            {'os_maker': '', 'os_name': 'DEC'},
            {'os_maker': '', 'os_name': 'VAX'},
            {'os_maker': '', 'os_name': 'Alpha'},
            {'os_maker': '', 'os_name': 'Itanium i2 and i4'},
            {'os_maker': '', 'os_name': 'WAITS'},
            {'os_maker': 'ENEA AB', 'os_name': 'OSE'},
            {'os_maker': 'Fujitsu', 'os_name': 'Towns OS'},
            {'os_maker': 'Fujitsu', 'os_name': 'OS/IV'},
            {'os_maker': 'Fujitsu', 'os_name': 'MSP'},
            {'os_maker': 'Fujitsu', 'os_name': 'MSP-EX'},
            {'os_maker': '',
             'os_name': 'Real-Time Multiprogramming Operating System'},
            {'os_maker': '', 'os_name': 'GCOS'},
            {'os_maker': '', 'os_name': 'Multics'},
            {'os_maker': 'Green Hills Software', 'os_name': 'INTEGRITY'},
            {'os_maker': 'Green Hills Software', 'os_name': 'INTEGRITY-178B'},
            {'os_maker': 'Green Hills Software', 'os_name': 'INTEGRITY'},
            {'os_maker': 'Green Hills Software', 'os_name': 'µ-velOSity'},
            {'os_maker': 'Green Hills Software', 'os_name': 'microkernel'},
            {'os_maker': 'Harris Corporation', 'os_name': 'Vulcan O/S'},
            {'os_maker': 'Harris Corporation', 'os_name': 'Harris UNIX'},
            {'os_maker': '', 'os_name': 'HDOS'},
            {'os_maker': '', 'os_name': 'H8'},
            {'os_maker': '', 'os_name': 'Zenith Z-89'},
            {'os_maker': '', 'os_name': 'HT-11'},
            {'os_maker': '', 'os_name': 'RT-11'},
            {'os_maker': '', 'os_name': 'Heathkit H11'},
            {'os_maker': '', 'os_name': 'HP Multi-Programming Executive'},
            {'os_maker': '', 'os_name': 'HP-UX'},
            {'os_maker': 'Honeywell', 'os_name': 'CP-6'},
            {'os_maker': 'Huawei', 'os_name': 'Harmony OS'},
            {'os_maker': 'Huawei', 'os_name': 'LiteOS'},
            {'os_maker': 'Intel Corporation', 'os_name': 'iRMX'},
            {'os_maker': 'Intel Corporation', 'os_name': 'ISIS'},
            {'os_maker': 'Intel Corporation', 'os_name': 'ISIS-II'},
            {'os_maker': 'Intel Corporation', 'os_name': 'Intellec'},
            {'os_maker': 'Intel Corporation', 'os_name': 'PL/M'},
            {'os_maker': 'International Computers Limited', 'os_name': 'J'},
            {'os_maker': 'International Computers Limited', 'os_name': 'MultiJob'},
            {'os_maker': 'International Computers Limited', 'os_name': 'GEORGE'},
            {'os_maker': 'International Computers Limited', 'os_name': 'ICL'},
            {'os_maker': 'International Computers Limited',
             'os_name': '1900 series'},
            {'os_maker': 'International Computers Limited', 'os_name': 'Executive'},
            {'os_maker': 'International Computers Limited', 'os_name': 'TME'},
            {'os_maker': 'International Computers Limited', 'os_name': 'ICL VME'},
            {'os_maker': 'International Computers Limited',
             'os_name': 'ICL 2900 Series'},
            {'os_maker': 'International Computers Limited', 'os_name': 'S3'},
            {'os_maker': 'International Computers Limited', 'os_name': 'VME/K'},
            {'os_maker': 'Jide', 'os_name': 'Remix OS'},
            {'os_maker': 'Jolla', 'os_name': 'Sailfish OS'},
            {'os_maker': 'KaiOS', 'os_name': 'KaiOS'},
            {'os_maker': '', 'os_name': 'LynxOS'},
            {'os_maker': 'Meizu', 'os_name': 'Flyme OS'},
            {'os_maker': 'Micrium Inc.', 'os_name': 'MicroC/OS-II'},
            {'os_maker': 'Micrium Inc.', 'os_name': 'MicroC/OS-III'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Xenix'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'SCO'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'MS-DOS'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'MSX-DOS'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'DOS/V'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'OS/2'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 1.0'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 2.0'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 3.0'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 3.1x'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows for Workgroups 3.1'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 3.2'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows for Workgroups 3.11'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 95'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 98'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Millennium Edition'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows NT'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows NT 3.1'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows NT 3.5'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows NT 3.51'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows NT 4.0'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 2000'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows XP'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Server 2003'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Fundamentals for Legacy PCs'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Vista'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Azure'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Home Server'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Server 2008'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 7'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Phone 7'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Server 2008 R2'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Home Server 2011'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 8'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows RT'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Phone 8'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Server 2012'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 8.1'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Phone 8.1'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Server 2012 R2'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 10'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 10 Mobile'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Server 2016'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Server 2019'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows 11'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows CE'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows CE 3.0'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows CE 5.0'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Embedded CE 6.0'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Embedded Compact 7'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Windows Embedded Compact 2013'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Windows Mobile'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Singularity'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'managed code'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'C#'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Midori'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Xbox system faker_software'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Xbox 360 system faker_software'},
            {'os_maker': 'Microsoft Corporation',
             'os_name': 'Xbox One system faker_software'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'Azure Sphere'},
            {'os_maker': 'Microsoft Corporation', 'os_name': 'ThreadX'},
            {'os_maker': 'MITS', 'os_name': 'Altair DOS'},
            {'os_maker': 'MITS', 'os_name': 'Altair 8800'},
            {'os_maker': 'MITS', 'os_name': 'citation needed'},
            {'os_maker': 'MontaVista', 'os_name': 'Mobilinux'},
            {'os_maker': 'NCR Corporation', 'os_name': 'TMX'},
            {'os_maker': 'NCR Corporation', 'os_name': 'IMOS'},
            {'os_maker': 'NCR Corporation', 'os_name': 'citation needed'},
            {'os_maker': 'NCR Corporation', 'os_name': 'VRX'},
            {'os_maker': 'Nintendo', 'os_name': 'ES'},
            {'os_maker': 'NeXT', 'os_name': 'NeXTSTEP'},
            {'os_maker': 'Novell', 'os_name': 'NetWare'},
            {'os_maker': 'Novell', 'os_name': 'UnixWare'},
            {'os_maker': 'Novell', 'os_name': 'Novell "SuperNOS"'},
            {'os_maker': 'Novell', 'os_name': 'Novell "Corsair"'},
            {'os_maker': 'Novell', 'os_name': 'Novell "Exposé"'},
            {'os_maker': 'Novell', 'os_name': 'Open Enterprise Server'},
            {'os_maker': 'Open Mobile Platform', 'os_name': 'Aurora OS'},
            {'os_maker': 'Open Mobile Platform', 'os_name': 'Aurora OS'},
            {'os_maker': 'Quadros Systems', 'os_name': 'RTXC Quadros'},
            {'os_maker': 'RCA', 'os_name': 'Time Sharing Operating System'},
            {'os_maker': 'RoweBots', 'os_name': 'DSPnano RTOS'},
            {'os_maker': 'Samsung Electronics', 'os_name': 'Bada'},
            {'os_maker': 'Samsung Electronics', 'os_name': 'Tizen'},
            {'os_maker': 'Samsung Electronics', 'os_name': 'Orsay'},
            {'os_maker': 'Samsung Electronics', 'os_name': 'One UI'},
            {'os_maker': 'Sinclair Research', 'os_name': 'Sinclair BASIC'},
            {'os_maker': 'Sinclair Research', 'os_name': 'Sinclair Research'},
            {'os_maker': 'Sinclair Research', 'os_name': 'Timex Sinclair'},
            {'os_maker': '', 'os_name': 'Xenix'},
            {'os_maker': '', 'os_name': 'Xenix'},
            {'os_maker': '', 'os_name': 'Xenix'},
            {'os_maker': '', 'os_name': 'SCO Unix'},
            {'os_maker': '', 'os_name': 'SCO Open Desktop'},
            {'os_maker': '', 'os_name': 'SCO Unix'},
            {'os_maker': '', 'os_name': 'SCO OpenServer'},
            {'os_maker': '', 'os_name': 'SCO OpenServer'},
            {'os_maker': '', 'os_name': 'UnixWare'},
            {'os_maker': '', 'os_name': 'UnixWare'},
            {'os_maker': '', 'os_name': 'UnixWare'},
            {'os_maker': '', 'os_name': 'SCO'},
            {'os_maker': '', 'os_name': 'Berkeley Timesharing System'},
            {'os_maker': '', 'os_name': 'SDS 940'},
            {'os_maker': 'SYSGO', 'os_name': 'PikeOS'},
            {'os_maker': '', 'os_name': 'NonStop OS'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'TRSDOS'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'TRS-80'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'Color BASIC'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'TRS-80 Color Computer'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'NewDos/80'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'DeskMate'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'Tandy 1000'},
            {'os_maker': 'Tandy Corporation', 'os_name': 'citation needed'},
            {'os_maker': '', 'os_name': 'Edos'},
            {'os_maker': '', 'os_name': 'DOS/360'},
            {'os_maker': '', 'os_name': 'DOS/VS'},
            {'os_maker': '', 'os_name': 'DOS/VSE'},
            {'os_maker': '', 'os_name': 'System/360'},
            {'os_maker': '', 'os_name': 'System/370'},
            {'os_maker': 'Texas Instruments', 'os_name': 'TI-RTOS Kernel'},
            {'os_maker': 'TRON Project', 'os_name': 'TRON'},
            {'os_maker': 'TRON Project', 'os_name': 'real-time operating system'},
            {'os_maker': 'TRON Project', 'os_name': 'kernel'},
            {'os_maker': 'TRON Project', 'os_name': 'T-Kernel'},
            {'os_maker': '', 'os_name': 'EXEC I'},
            {'os_maker': '', 'os_name': 'EXEC II'},
            {'os_maker': '', 'os_name': 'EXEC 8'},
            {'os_maker': '', 'os_name': 'OS 2200'},
            {'os_maker': '', 'os_name': 'VS/9'},
            {'os_maker': '', 'os_name': 'RCA TSOS'},
            {'os_maker': 'Wang Laboratories', 'os_name': 'WPS'},
            {'os_maker': 'Wang Laboratories', 'os_name': 'OIS'},
            {'os_maker': 'Wind River Systems', 'os_name': 'VxWorks'},
            {'os_maker': 'Zilog', 'os_name': 'Z80-RIO'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'MINIX'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Andrew S. Tanenbaum'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Netherlands'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'BSD'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'DEC'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'VAX'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'FreeBSD'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'CSRG'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'DragonFlyBSD'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'MidnightBSD'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'GhostBSD'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'TrueOS'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'NetBSD'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'OpenBSD'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Bitrig'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Darwin'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'GNU'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Linux'},
            {'os_maker': 'Unix or Unix-like',
             'os_name': 'List of Linux distributions'},
            {'os_maker': 'Unix or Unix-like',
             'os_name': 'GNU/Linux naming controversy'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Android'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Android-x86'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Remix OS'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Redox'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'OpenSolaris'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'illumos'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'OpenSolaris'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Solaris'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'OpenIndiana'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'OS/Net'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'OpenSolaris'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Solaris'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Nexenta OS'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'SmartOS'},
            {'os_maker': 'Unix or Unix-like',
             'os_name': 'Kernel-based Virtual Machine'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'RTEMS'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Syllable Desktop'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'VSTa'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Plurix'},
            {'os_maker': 'Unix or Unix-like',
             'os_name': 'Federal University of Rio de Janeiro'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'TUNIS'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Xv6'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'SerenityOS'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Microsoft Windows'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Mac OS'},
            {'os_maker': 'Non-Unix', 'os_name': 'Cosmos'},
            {'os_maker': 'Non-Unix', 'os_name': 'FreeDOS'},
            {'os_maker': 'Non-Unix', 'os_name': 'Genode'},
            {'os_maker': 'Non-Unix', 'os_name': 'Ghost OS'},
            {'os_maker': 'Non-Unix', 'os_name': 'Haiku'},
            {'os_maker': 'Non-Unix', 'os_name': 'BeOS'},
            {'os_maker': 'Non-Unix', 'os_name': 'Incompatible Timesharing System'},
            {'os_maker': 'Non-Unix', 'os_name': 'macro assembler'},
            {'os_maker': 'Non-Unix', 'os_name': 'PDP-6'},
            {'os_maker': 'Non-Unix', 'os_name': 'PDP-10'},
            {'os_maker': 'Non-Unix', 'os_name': 'MIT'},
            {'os_maker': 'Non-Unix', 'os_name': 'osFree'},
            {'os_maker': 'Non-Unix', 'os_name': 'OSv'},
            {'os_maker': 'Non-Unix', 'os_name': 'Phantom OS'},
            {'os_maker': 'Non-Unix', 'os_name': 'ReactOS'},
            {'os_maker': 'Non-Unix', 'os_name': 'Windows NT'},
            {'os_maker': 'Non-Unix', 'os_name': 'Windows XP'},
            {'os_maker': 'Non-Unix', 'os_name': 'Windows 2000'},
            {'os_maker': 'Non-Unix', 'os_name': 'SharpOS'},
            {'os_maker': 'Non-Unix', 'os_name': 'TempleOS'},
            {'os_maker': 'Non-Unix', 'os_name': 'Visopsys'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Plan 9 from Bell Labs'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Bell Labs'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Inferno'},
            {'os_maker': 'Unix or Unix-like', 'os_name': 'Research Unix'},
            {'os_maker': 'Non-Unix', 'os_name': 'Amoeba'},
            {'os_maker': 'Non-Unix', 'os_name': 'Andrew S. Tanenbaum'},
            {'os_maker': 'Non-Unix', 'os_name': 'Barrelfish'},
            {'os_maker': 'Non-Unix', 'os_name': 'Croquet'},
            {'os_maker': 'Non-Unix', 'os_name': 'EROS'},
            {'os_maker': 'Non-Unix', 'os_name': 'CapROS'},
            {'os_maker': 'Non-Unix', 'os_name': 'Harmony'},
            {'os_maker': 'Non-Unix', 'os_name': 'HelenOS'},
            {'os_maker': 'Non-Unix', 'os_name': 'House'},
            {'os_maker': 'Non-Unix', 'os_name': 'ILIOS'},
            {'os_maker': 'Non-Unix', 'os_name': 'L4'},
            {'os_maker': 'Non-Unix', 'os_name': 'Mach'},
            {'os_maker': 'Non-Unix', 'os_name': 'Carnegie Mellon University'},
            {'os_maker': 'Non-Unix', 'os_name': 'NeXTSTEP'},
            {'os_maker': 'Non-Unix', 'os_name': 'Nemesis'},
            {'os_maker': 'Non-Unix', 'os_name': 'Singularity'},
            {'os_maker': 'Non-Unix', 'os_name': 'managed code'},
            {'os_maker': 'Non-Unix', 'os_name': 'dependable'},
            {'os_maker': 'Non-Unix', 'os_name': 'Spring'},
            {'os_maker': 'Non-Unix', 'os_name': 'THE multiprogramming system'},
            {'os_maker': 'Non-Unix',
             'os_name': 'Eindhoven University of Technology'},
            {'os_maker': 'Non-Unix', 'os_name': 'Thoth'},
            {'os_maker': 'Non-Unix', 'os_name': 'University of Waterloo'},
            {'os_maker': 'Non-Unix', 'os_name': 'V'},
            {'os_maker': 'Non-Unix', 'os_name': 'Verve'},
            {'os_maker': 'Non-Unix', 'os_name': 'type safety'},
            {'os_maker': 'Non-Unix', 'os_name': 'memory safety'},
            {'os_maker': 'Non-Unix', 'os_name': 'Xinu'},
            {'os_maker': 'Non-Unix', 'os_name': 'Douglas E. Comer'},
            {'os_maker': 'Routers', 'os_name': 'CatOS'},
            {'os_maker': 'Routers', 'os_name': 'Cisco Systems'},
            {'os_maker': 'Routers', 'os_name': 'Cisco IOS'},
            {'os_maker': 'Routers', 'os_name': 'Cisco Systems'},
            {'os_maker': 'Routers', 'os_name': 'Inferno'},
            {'os_maker': 'Routers', 'os_name': 'Bell Labs'},
            {'os_maker': 'Routers', 'os_name': 'IOS-XR'},
            {'os_maker': 'Routers', 'os_name': 'Cisco Systems'},
            {'os_maker': 'Routers', 'os_name': 'JunOS'},
            {'os_maker': 'Routers', 'os_name': 'Juniper Networks'},
            {'os_maker': 'Routers', 'os_name': 'LANCOM Systems'},
            {'os_maker': 'Routers', 'os_name': 'Linux'},
            {'os_maker': 'Routers', 'os_name': 'OpenWrt'},
            {'os_maker': 'Routers', 'os_name': 'DD-WRT'},
            {'os_maker': 'Routers', 'os_name': 'LEDE'},
            {'os_maker': 'Routers', 'os_name': 'Gargoyle'},
            {'os_maker': 'Routers', 'os_name': 'LibreCMC'},
            {'os_maker': 'Routers', 'os_name': 'Zeroshell'},
            {'os_maker': 'Routers', 'os_name': 'RTOS'},
            {'os_maker': 'Routers', 'os_name': 'm0n0wall'},
            {'os_maker': 'Routers', 'os_name': 'OPNsense'},
            {'os_maker': 'Routers', 'os_name': 'pfsense'},
            {'os_maker': 'Routers',
             'os_name': 'List of wireless router firmware projects'},
            {'os_maker': 'Other embedded', 'os_name': 'Apache Mynewt'},
            {'os_maker': 'Other embedded', 'os_name': 'ChibiOS/RT'},
            {'os_maker': 'Other embedded', 'os_name': 'Contiki'},
            {'os_maker': 'Other embedded', 'os_name': 'ERIKA Enterprise'},
            {'os_maker': 'Other embedded', 'os_name': 'eCos'},
            {'os_maker': 'Other embedded', 'os_name': 'NetBSD'},
            {'os_maker': 'Other embedded', 'os_name': 'Nucleus RTOS'},
            {'os_maker': 'Other embedded', 'os_name': 'NuttX'},
            {'os_maker': 'Other embedded', 'os_name': 'Minix'},
            {'os_maker': 'Other embedded', 'os_name': 'NCOS'},
            {'os_maker': 'Other embedded',
             'os_name': 'freeRTOS, openRTOS, safeRTOS'},
            {'os_maker': 'Other embedded', 'os_name': 'OpenEmbedded'},
            {'os_maker': 'Other embedded', 'os_name': 'Yocto Project'},
            {'os_maker': 'Other embedded', 'os_name': 'pSOS'},
            {'os_maker': 'Other embedded', 'os_name': 'QNX'},
            {'os_maker': 'Other embedded', 'os_name': 'REX OS'},
            {'os_maker': 'Other embedded', 'os_name': 'RIOT'},
            {'os_maker': 'Other embedded', 'os_name': 'ROM-DOS'},
            {'os_maker': 'Other embedded', 'os_name': 'TinyOS'},
            {'os_maker': 'Other embedded', 'os_name': 'ThreadX'},
            {'os_maker': 'Other embedded', 'os_name': 'RT-Thread'},
            {'os_maker': 'Other embedded', 'os_name': 'DSPnano RTOS'},
            {'os_maker': 'Other embedded', 'os_name': 'Windows IoT'},
            {'os_maker': 'Other embedded', 'os_name': 'Windows Embedded'},
            {'os_maker': 'Other embedded', 'os_name': 'Windows CE'},
            {'os_maker': 'Other embedded', 'os_name': 'Windows IoT Core'},
            {'os_maker': 'Other embedded', 'os_name': 'Windows IoT Enterprise'},
            {'os_maker': 'Other embedded', 'os_name': 'VxWorks'},
            {'os_maker': 'Other embedded', 'os_name': 'Wombat'},
            {'os_maker': 'Other embedded', 'os_name': 'microkernel'},
            {'os_maker': 'Other embedded', 'os_name': 'real-time'},
            {'os_maker': 'Other embedded', 'os_name': 'embedded'},
            {'os_maker': 'Other embedded', 'os_name': 'Zephyr'},
            {'os_maker': 'LEGO Mindstorms', 'os_name': 'brickOS'},
            {'os_maker': 'LEGO Mindstorms', 'os_name': 'leJOS'},
            {'os_maker': 'Category links', 'os_name': 'Operating systems'},
            {'os_maker': 'Category links', 'os_name': 'Embedded operating systems'},
            {'os_maker': 'Category links', 'os_name': 'Real-time operating systems'}]
